import {
  Servicio,
  Colaborador,
  Cita,
  BloqueoDisponibilidad,
  ConfiguracionSalon,
  Especialidad,
  Producto,
  TransaccionFinanciera,
} from '@/types/salon';

/**
 * Genera la contraseña por defecto para una colaboradora o usuario según su nombre:
 * Primer nombre en minúsculas sin acentos + "123" (ej. "Valentina Ramos" -> "valentina123")
 */
export function generarPasswordPorDefecto(nombre: string): string {
  if (!nombre || !nombre.trim()) return 'colab123';
  const primerNombre = nombre.trim().split(' ')[0].toLowerCase();
  const limpio = primerNombre.normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]/g, '');
  return `${limpio || 'colab'}123`;
}

export const ESPECIALIDADES_INICIALES: Especialidad[] = [
  { id: 'pestanas', nombre: 'Pestañas & Cejas', icono: 'Eye', color: '#A855F7' },
  { id: 'unas', nombre: 'Uñas & Manicura', icono: 'Gem', color: '#E07A5F' },
  { id: 'cabello', nombre: 'Cabello & Estilismo', icono: 'Scissors', color: '#818CF8' },
  { id: 'faciales', nombre: 'Tratamientos Faciales', icono: 'Smile', color: '#10B981' },
  { id: 'depilacion', nombre: 'Depilación Láser e Hilo', icono: 'Zap', color: '#F59E0B' },
  { id: 'masajes', nombre: 'Masajes Corporales', icono: 'HandMetal', color: '#14B8A6' },
];

export const CONFIG_INICIAL: ConfiguracionSalon = {
  nombreSalon: 'Pierina Salón',
  eslogan: 'Cejas, pestañas y más',
  logoUrl: '/logo-pierina.png',
  telefonoSalon: '+507 6123-4567',
  direccion: 'Ciudad de Panamá, Panamá',
  horarioApertura: '08:00',
  horarioCierre: '23:00',
  intervaloMinutos: 30,
  pinAdmin: 'admin123',
  pinSuperAdmin: 'onix1974',
  administradores: [],
  alertaSonoraActiva: true,
  moneda: '$',
  maxColaboradores: 50,
  maxAdministradores: 10,
  zonaHoraria: 'America/Panama',
  especialidades: ESPECIALIDADES_INICIALES,
  moduloInventarioYFinanzasActivo: false,
  impuestoPorcentaje: 7.0,
  nombreImpuesto: 'ITBMS (7%)',
  comisionServiciosPorcentaje: 50,
  comisionProductosPorcentaje: 10,
  salarioBasePredeterminado: 0,
  esquemaNominaDefault: 'comision',
  firebaseConfig: {
    apiKey: 'AIzaSyC2HdTRwA3rXLc6sXzj_GwM43Jpn3EGPbw',
    authDomain: 'pierina-1ee38.firebaseapp.com',
    projectId: 'pierina-1ee38',
    storageBucket: 'pierina-1ee38.firebasestorage.app',
    messagingSenderId: '128506779169',
    appId: '1:128506779169:web:3b467a26a0253bcde87560',
  },
};

export const SERVICIOS_INICIALES: Servicio[] = [
  // 1. Uñas
  {
    id: 'serv-u-1',
    nombre: 'Manicura Rusa + Esmaltado Semi Jelly',
    categoria: 'unas',
    duracionMin: 60,
    precio: 480,
    descripcion: 'Limpieza profunda de cutícula con técnica combinada y acabado brillo espejo de larga duración (hasta 21 días).',
    icono: 'Sparkles',
    activo: true,
  },
  {
    id: 'serv-u-2',
    nombre: 'Esculturales Soft Gel / Polygel con Nail Art',
    categoria: 'unas',
    duracionMin: 90,
    precio: 750,
    descripcion: 'Extensión ligera, resistente y natural con diseño personalizado a mano alzada.',
    icono: 'Gem',
    activo: true,
  },
  {
    id: 'serv-u-3',
    nombre: 'Pedicura Spa Detox & Masaje Podal',
    categoria: 'unas',
    duracionMin: 60,
    precio: 520,
    descripcion: 'Exfoliación con sales minerales del Himalaya, retiro de durezas, mascarilla hidratante y esmaltado.',
    icono: 'Footprints',
    activo: true,
  },

  // 2. Cabello
  {
    id: 'serv-c-1',
    nombre: 'Corte de Autor + Ritual Glow & Peinado',
    categoria: 'cabello',
    duracionMin: 60,
    precio: 550,
    descripcion: 'Diagnóstico capilar personalizado, lavado relajante con masaje craneal, corte y peinado con ondas o lacio sedoso.',
    icono: 'Scissors',
    activo: true,
  },
  {
    id: 'serv-c-2',
    nombre: 'Balayage Francés & Baño de Brillo Gloss',
    categoria: 'cabello',
    duracionMin: 150,
    precio: 1850,
    descripcion: 'Degradado sutil con iluminación orgánica, matiz de alta costura y tratamiento de plex reconstituyente.',
    icono: 'Palette',
    activo: true,
  },
  {
    id: 'serv-c-3',
    nombre: 'Botox Capilar Reconstructor con Ácido Hialurónico',
    categoria: 'cabello',
    duracionMin: 90,
    precio: 980,
    descripcion: 'Elimina el frizz al 100%, sella la cutícula y devuelve brillo y movimiento sin restar volumen.',
    icono: 'Wand2',
    activo: true,
  },

  // 3. Faciales
  {
    id: 'serv-f-1',
    nombre: 'Limpieza Facial Profunda + Hidrodermoabrasión',
    categoria: 'faciales',
    duracionMin: 75,
    precio: 850,
    descripcion: 'Extracción ultrasónica, succión de impurezas con infusión de sérums, alta frecuencia y mascarilla hidroplástica.',
    icono: 'Smile',
    activo: true,
  },
  {
    id: 'serv-f-2',
    nombre: 'Peeling Luminosidad Efecto Porcelana (Glow Peeling)',
    categoria: 'faciales',
    duracionMin: 60,
    precio: 950,
    descripcion: 'Renovación celular no invasiva para manchas, poros abiertos y textura irregular con vitamina C pura.',
    icono: 'Sun',
    activo: true,
  },

  // 4. Depilación
  {
    id: 'serv-d-1',
    nombre: 'Depilación Láser Diodo Trionda (Cuerpo Completo)',
    categoria: 'depilacion',
    duracionMin: 60,
    precio: 1600,
    descripcion: 'Tecnología indolora con cabezal frío de zafiro apta para todo tipo de piel y vello.',
    icono: 'Zap',
    activo: true,
  },
  {
    id: 'serv-d-2',
    nombre: 'Depilación Facial con Hilo Orgánico & Caléndula',
    categoria: 'depilacion',
    duracionMin: 30,
    precio: 250,
    descripcion: 'Técnica milenaria higiénica y precisa que no irrita la piel sensible.',
    icono: 'Feather',
    activo: true,
  },

  // 5. Pestañas y Cejas
  {
    id: 'serv-p-1',
    nombre: 'Lifting de Pestañas Queratina + Tinte Negro Intenso',
    categoria: 'pestanas',
    duracionMin: 60,
    precio: 520,
    descripcion: 'Eleva y arquea tus pestañas naturales desde la raíz con nutrición profunda de botox queratínico.',
    icono: 'Eye',
    activo: true,
  },
  {
    id: 'serv-p-2',
    nombre: 'Laminado de Cejas (Brow Lamination) & Diseño con Henna',
    categoria: 'pestanas',
    duracionMin: 45,
    precio: 480,
    descripcion: 'Cejas peinadas, definidas y con efecto microblading temporal para enmarcar la mirada.',
    icono: 'EyeOff',
    activo: true,
  },

  // 6. Masajes corporales
  {
    id: 'serv-m-1',
    nombre: 'Masaje Relajante con Aromaterapia & Piedras Calientes',
    categoria: 'masajes',
    duracionMin: 60,
    precio: 790,
    descripcion: 'Técnica envolvente con aceites esenciales de lavanda y jazmín para disolver la tensión y el estrés.',
    icono: 'HandMetal',
    activo: true,
  },
  {
    id: 'serv-m-2',
    nombre: 'Masaje Descontracturante Profundo Espalda & Cuello',
    categoria: 'masajes',
    duracionMin: 60,
    precio: 850,
    descripcion: 'Enfocado en nudos musculares causados por mala postura, fatiga o actividad física intensa.',
    icono: 'Activity',
    activo: true,
  },
];

// Colaboradoras sin fotos ficticias (se visualizan con iniciales elegantes y permiten subir su propia foto real)
export const COLABORADORES_INICIALES: Colaborador[] = [
  {
    id: 'colab-pierina',
    nombre: 'Pierina',
    foto: null,
    pin: 'pierina123',
    passwordOriginal: 'pierina123',
    especialidades: ['pestanas', 'unas', 'faciales'],
    telefono: '+507 6123-4567',
    color: '#B85D75',
    activo: true,
    accesoRestringido: false,
    rol: 'colaborador',
    biografia: 'Especialista en cejas, pestañas, manicura y tratamientos faciales de autor.',
    serviciosAsignados: [
      { servicioId: 'serv-p-1', precioPersonalizado: 520, activo: true },
      { servicioId: 'serv-p-2', precioPersonalizado: 480, activo: true },
      { servicioId: 'serv-u-1', precioPersonalizado: 480, activo: true },
      { servicioId: 'serv-f-1', precioPersonalizado: 850, activo: true },
    ],
    horarioBase: {
      dias: [1, 2, 3, 4, 5, 6],
      horaInicio: '08:00',
      horaFin: '20:00',
      descansoInicio: '13:00',
      descansoFin: '14:00',
    },
  },
  {
    id: 'colab-1',
    nombre: 'Valentina Ramos',
    foto: null, // Sin foto ficticia -> avatar monograma con opción a subir foto real
    pin: 'valentina123',
    passwordOriginal: 'valentina123',
    especialidades: ['unas', 'pestanas'],
    telefono: '+507 6123-4567',
    color: '#E07A5F',
    activo: true,
    accesoRestringido: false,
    rol: 'colaborador',
    biografia: 'Especialista en Manicura Rusa, Soft Gel y diseño de miradas.',
    serviciosAsignados: [
      { servicioId: 'serv-u-1', precioPersonalizado: 480, activo: true },
      { servicioId: 'serv-u-2', precioPersonalizado: 750, activo: true },
      { servicioId: 'serv-u-3', precioPersonalizado: 520, activo: true },
      { servicioId: 'serv-p-1', precioPersonalizado: 520, activo: true },
      { servicioId: 'serv-p-2', precioPersonalizado: 480, activo: true },
    ],
    horarioBase: {
      dias: [1, 2, 3, 4, 5, 6],
      horaInicio: '09:00',
      horaFin: '18:30',
      descansoInicio: '14:00',
      descansoFin: '15:00',
    },
  },
  {
    id: 'colab-2',
    nombre: 'Sofía Morales',
    foto: null,
    pin: 'sofia123',
    passwordOriginal: 'sofia123',
    especialidades: ['cabello'],
    telefono: '+507 6234-5678',
    color: '#818CF8',
    activo: true,
    accesoRestringido: false,
    rol: 'colaborador',
    biografia: 'Colorista y estilista en balayage francés y diseño de corte.',
    serviciosAsignados: [
      { servicioId: 'serv-c-1', precioPersonalizado: 550, activo: true },
      { servicioId: 'serv-c-2', precioPersonalizado: 1850, activo: true },
      { servicioId: 'serv-c-3', precioPersonalizado: 980, activo: true },
    ],
    horarioBase: {
      dias: [2, 3, 4, 5, 6, 0],
      horaInicio: '10:00',
      horaFin: '19:30',
      descansoInicio: '14:30',
      descansoFin: '15:30',
    },
  },
  {
    id: 'colab-3',
    nombre: 'Camila Silva',
    foto: null,
    pin: 'camila123',
    passwordOriginal: 'camila123',
    especialidades: ['faciales', 'depilacion'],
    telefono: '+507 6345-6789',
    color: '#10B981',
    activo: true,
    accesoRestringido: false,
    rol: 'colaborador',
    biografia: 'Cosmiatra en rejuvenecimiento facial y depilación láser.',
    serviciosAsignados: [
      { servicioId: 'serv-f-1', precioPersonalizado: 850, activo: true },
      { servicioId: 'serv-f-2', precioPersonalizado: 950, activo: true },
      { servicioId: 'serv-d-1', precioPersonalizado: 1600, activo: true },
      { servicioId: 'serv-d-2', precioPersonalizado: 250, activo: true },
    ],
    horarioBase: {
      dias: [1, 2, 3, 4, 5, 6],
      horaInicio: '09:30',
      horaFin: '19:00',
      descansoInicio: '13:30',
      descansoFin: '14:30',
    },
  },
  {
    id: 'colab-4',
    nombre: 'Elena Castillo',
    foto: null,
    pin: 'elena123',
    passwordOriginal: 'elena123',
    especialidades: ['masajes', 'faciales'],
    telefono: '+507 6456-7890',
    color: '#F59E0B',
    activo: true,
    accesoRestringido: false,
    rol: 'colaborador',
    biografia: 'Especialista en masoterapia descontracturante y spa.',
    serviciosAsignados: [
      { servicioId: 'serv-m-1', precioPersonalizado: 790, activo: true },
      { servicioId: 'serv-m-2', precioPersonalizado: 850, activo: true },
      { servicioId: 'serv-f-1', precioPersonalizado: 850, activo: true },
    ],
    horarioBase: {
      dias: [1, 3, 4, 5, 6, 0],
      horaInicio: '11:00',
      horaFin: '20:00',
      descansoInicio: '15:00',
      descansoFin: '16:00',
    },
  },
];

export const TERAPEUTAS_INICIALES = COLABORADORES_INICIALES;

// Generar fechas relativas para citas de demostración
const hoy = new Date();
const formatFecha = (d: Date) => d.toISOString().split('T')[0];

const fechaHoy = formatFecha(hoy);
const fechaManana = formatFecha(new Date(hoy.getTime() + 86400000));
const fechaPasado = formatFecha(new Date(hoy.getTime() + 86400000 * 2));

export const CITAS_INICIALES: Cita[] = [
  {
    id: 'cita-demo-1',
    codigo: 'PIER-4192',
    clienteNombre: 'Mariana Gómez Lozano',
    clienteTelefono: '+507 6987-6543',
    clienteNotas: 'Es mi primera vez. Prefiero tono rosa nude y cutícula sensible.',
    fotoReferencia: null,
    terapeutaId: 'colab-1',
    colaboradorId: 'colab-1',
    servicioIds: ['serv-u-1'],
    fecha: fechaHoy,
    horaInicio: '10:00',
    horaFin: '11:00',
    precioTotal: 480,
    duracionTotalMin: 60,
    estado: 'Confirmada',
    creadoEn: new Date(hoy.getTime() - 3600000 * 24).toISOString(),
    origen: 'web_cliente',
  },
  {
    id: 'cita-demo-2',
    codigo: 'PIER-8821',
    clienteNombre: 'Daniela Alarcón',
    clienteTelefono: '+507 6765-4321',
    clienteNotas: 'Solicito valoración para cambio de tono a cobrizo.',
    fotoReferencia: null,
    terapeutaId: 'colab-2',
    colaboradorId: 'colab-2',
    servicioIds: ['serv-c-2'],
    fecha: fechaHoy,
    horaInicio: '11:30',
    horaFin: '14:00',
    precioTotal: 1850,
    duracionTotalMin: 150,
    estado: 'Pendiente',
    creadoEn: new Date(hoy.getTime() - 600000).toISOString(),
    origen: 'web_cliente',
  },
  {
    id: 'cita-demo-3',
    codigo: 'PIER-3310',
    clienteNombre: 'Patricia Trejo',
    clienteTelefono: '+507 6654-3210',
    clienteNotas: 'Piel con tendencia grasa en zona T.',
    fotoReferencia: null,
    terapeutaId: 'colab-3',
    colaboradorId: 'colab-3',
    servicioIds: ['serv-f-1'],
    fecha: fechaManana,
    horaInicio: '10:30',
    horaFin: '11:45',
    precioTotal: 850,
    duracionTotalMin: 75,
    estado: 'Confirmada',
    creadoEn: new Date(hoy.getTime() - 3600000 * 12).toISOString(),
    origen: 'web_cliente',
  },
  {
    id: 'cita-demo-4',
    codigo: 'PIER-9945',
    clienteNombre: 'Andrea Valenzuela',
    clienteTelefono: '+507 6554-3210',
    clienteNotas: 'Tensión acumulada en trapecios y cervicales.',
    fotoReferencia: null,
    terapeutaId: 'colab-4',
    colaboradorId: 'colab-4',
    servicioIds: ['serv-m-2'],
    fecha: fechaPasado,
    horaInicio: '16:00',
    horaFin: '17:00',
    precioTotal: 850,
    duracionTotalMin: 60,
    estado: 'Pendiente',
    creadoEn: new Date(hoy.getTime() - 3600000 * 2).toISOString(),
    origen: 'web_cliente',
  },
];

export const BLOQUEOS_INICIALES: BloqueoDisponibilidad[] = [
  {
    id: 'bloq-1',
    terapeutaId: 'colab-1',
    colaboradorId: 'colab-1',
    fecha: fechaManana,
    tipo: 'franja_horaria',
    horaInicio: '15:00',
    horaFin: '17:00',
    motivo: 'Capacitación Técnica Rusa Nail Art 2026',
    creadoEn: new Date().toISOString(),
  },
];

export const PRODUCTOS_INICIALES: Producto[] = [
  {
    id: 'prod-1',
    sku: 'BEA-7001',
    nombre: 'Aceite Reparador de Cutículas con Vitamina E (30ml)',
    categoria: 'unas',
    imagenUrl: null,
    precioCosto: 8.5,
    precioVenta: 18.0,
    stock: 14,
    stockMinimo: 4,
    activo: true,
    creadoEn: new Date(hoy.getTime() - 86400000 * 30).toISOString(),
  },
  {
    id: 'prod-2',
    sku: 'BEA-7002',
    nombre: 'Serum Facial Ácido Hialurónico & C (50ml)',
    categoria: 'faciales',
    imagenUrl: null,
    precioCosto: 14.0,
    precioVenta: 32.0,
    stock: 8,
    stockMinimo: 3,
    activo: true,
    creadoEn: new Date(hoy.getTime() - 86400000 * 25).toISOString(),
  },
  {
    id: 'prod-3',
    sku: 'BEA-7003',
    nombre: 'Shampoo Matizador Profesional Blonde Platinum (250ml)',
    categoria: 'cabello',
    imagenUrl: null,
    precioCosto: 12.0,
    precioVenta: 26.5,
    stock: 6,
    stockMinimo: 2,
    activo: true,
    creadoEn: new Date(hoy.getTime() - 86400000 * 20).toISOString(),
  },
  {
    id: 'prod-4',
    sku: 'BEA-7004',
    nombre: 'Mascarilla Capilar Reparación Profunda Argán (200g)',
    categoria: 'cabello',
    imagenUrl: null,
    precioCosto: 11.5,
    precioVenta: 25.0,
    stock: 10,
    stockMinimo: 3,
    activo: true,
    creadoEn: new Date(hoy.getTime() - 86400000 * 15).toISOString(),
  },
  {
    id: 'prod-5',
    sku: 'BEA-7005',
    nombre: 'Kit Espuma Limpiadora para Extensiones de Pestañas',
    categoria: 'pestanas',
    imagenUrl: null,
    precioCosto: 7.0,
    precioVenta: 16.0,
    stock: 3,
    stockMinimo: 5,
    activo: true,
    creadoEn: new Date(hoy.getTime() - 86400000 * 10).toISOString(),
  },
];

export const TRANSACCIONES_INICIALES: TransaccionFinanciera[] = [
  {
    id: 'tx-demo-1',
    tipo: 'ingreso_servicio',
    descripcion: 'Manicura Rusa + Esmaltado Semi Jelly - Mariana Gómez',
    montoBruto: 44.86,
    impuestoMonto: 3.14,
    montoTotal: 48.0,
    impuestoPorcentaje: 7.0,
    categoria: 'unas',
    fecha: fechaHoy,
    hora: '11:05',
    metodoPago: 'tarjeta',
    colaboradorId: 'colab-1',
    colaboradorNombre: 'Valentina Ramos',
    citaId: 'cita-demo-1',
    creadoEn: new Date(hoy.getTime() - 3600000 * 2).toISOString(),
  },
  {
    id: 'tx-demo-2',
    tipo: 'ingreso_producto',
    descripcion: 'Venta mostrador: 2x Aceite Reparador de Cutículas',
    montoBruto: 33.64,
    impuestoMonto: 2.36,
    montoTotal: 36.0,
    impuestoPorcentaje: 7.0,
    categoria: 'unas',
    fecha: fechaHoy,
    hora: '12:30',
    metodoPago: 'yappy_nequi',
    colaboradorId: 'colab-1',
    colaboradorNombre: 'Valentina Ramos',
    productoId: 'prod-1',
    cantidad: 2,
    creadoEn: new Date(hoy.getTime() - 3600000 * 1).toISOString(),
  },
  {
    id: 'tx-demo-3',
    tipo: 'egreso_mantenimiento',
    descripcion: 'Mantenimiento preventivo aires acondicionados salón',
    montoBruto: 75.0,
    impuestoMonto: 0.0,
    montoTotal: 75.0,
    impuestoPorcentaje: 7.0,
    categoria: 'mantenimiento',
    fecha: fechaHoy,
    hora: '09:00',
    metodoPago: 'transferencia',
    creadoEn: new Date(hoy.getTime() - 3600000 * 5).toISOString(),
  },
  {
    id: 'tx-demo-4',
    tipo: 'egreso_insumos',
    descripcion: 'Compra de toallas desechables, guantes y sanitizantes',
    montoBruto: 45.0,
    impuestoMonto: 3.15,
    montoTotal: 48.15,
    impuestoPorcentaje: 7.0,
    categoria: 'insumos',
    fecha: fechaHoy,
    hora: '10:00',
    metodoPago: 'efectivo',
    creadoEn: new Date(hoy.getTime() - 3600000 * 4).toISOString(),
  },
];
